version: 2
jobs:
  build_mass_docker_image:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            sudo pip install .
            python build_all.py

workflows:
  version: 2
  my-workflow:
    jobs:
      - build_mass_docker_image:
          context: sanhe-docker-hub
